"""baseline tables

Revision ID: 313b0960b510
Revises:
Create Date: 2026-09-14 11:22:04.961196

"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = "313b0960b510"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "contract",
        sa.Column("contract_no", sa.String(length=64), nullable=False, comment="合同编号"),
        sa.Column("title", sa.String(length=255), nullable=False, comment="合同名称"),
        sa.Column(
            "contract_type",
            sa.String(length=32),
            nullable=False,
            comment="合同类型，取值见 constants.ContractType",
        ),
        sa.Column("our_party", sa.String(length=255), nullable=True, comment="我方主体"),
        sa.Column("counterparty", sa.String(length=255), nullable=True, comment="相对方主体"),
        sa.Column(
            "amount", sa.Numeric(precision=18, scale=2), nullable=True, comment="合同金额（禁止 float）"
        ),
        sa.Column("currency", sa.CHAR(length=3), nullable=True, comment="币种，如 CNY"),
        sa.Column("sign_date", sa.Date(), nullable=True, comment="签署日"),
        sa.Column("effective_date", sa.Date(), nullable=True, comment="生效日"),
        sa.Column("expire_date", sa.Date(), nullable=True, comment="到期日"),
        sa.Column("dept", sa.String(length=64), nullable=True, comment="送审部门"),
        sa.Column(
            "applicant_id",
            sa.BigInteger(),
            nullable=True,
            comment="申请人 sys_user.id。⚠️ sys_user 属 P4，P3 暂不建 FK，P4 完成后通过增量迁移补",
        ),
        sa.Column(
            "source",
            sa.String(length=16),
            nullable=False,
            comment="合同来源，取值见 constants.ContractSource",
        ),
        sa.Column(
            "approval_instance_id",
            sa.BigInteger(),
            nullable=True,
            comment="关联审批单 approval_instance.id。刻意不建 FK：§7.2 未标注，且可避免与 approval_instance.contract_id 形成循环外键",
        ),
        sa.Column(
            "current_task_id",
            sa.BigInteger(),
            nullable=True,
            comment="最近一次审查任务 review_task.id（冗余，避免列表页 join）。刻意不建 FK：与 review_task.contract_id 构成循环依赖，且 §7.2 已明确其为冗余字段",
        ),
        sa.Column(
            "status",
            sa.String(length=16),
            nullable=False,
            comment="派生字段：跟随 current_task 的状态，便于列表筛选。由 P5 建合同时连同任务一起写入",
        ),
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False, comment="主键"),
        sa.Column("created_at", mysql.DATETIME(fsp=3), nullable=False, comment="创建时间（UTC）"),
        sa.Column("updated_at", mysql.DATETIME(fsp=3), nullable=False, comment="更新时间（UTC）"),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_contract")),
        sa.UniqueConstraint("contract_no", name=op.f("uq_contract_contract_no")),
    )
    op.create_table(
        "review_rule_set",
        sa.Column(
            "name", sa.String(length=128), nullable=False, comment="规则集名称，如「采购合同审查清单 v1」"
        ),
        sa.Column(
            "contract_type",
            sa.String(length=32),
            nullable=False,
            comment="适用的合同类型，取值见 constants.ContractType",
        ),
        sa.Column("description", sa.String(length=512), nullable=True, comment="说明"),
        sa.Column("version", sa.String(length=32), nullable=False, comment="规则集版本，参与任务幂等键计算"),
        sa.Column("is_active", sa.Boolean(), nullable=False, comment="是否启用"),
        sa.Column(
            "created_by",
            sa.BigInteger(),
            nullable=True,
            comment="创建者 sys_user.id（sys_user 属 P4，暂不建 FK）",
        ),
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False, comment="主键"),
        sa.Column("created_at", mysql.DATETIME(fsp=3), nullable=False, comment="创建时间（UTC）"),
        sa.Column("updated_at", mysql.DATETIME(fsp=3), nullable=False, comment="更新时间（UTC）"),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_review_rule_set")),
    )
    op.create_table(
        "sync_cursor",
        sa.Column(
            "source",
            sa.String(length=64),
            nullable=False,
            comment="数据源标识。⚠️ 唯一性未定义，P3 不加 UNIQUE（裁决 E）",
        ),
        sa.Column(
            "cursor_value", sa.String(length=255), nullable=True, comment="游标值（如上次拉取到的外部 ID）"
        ),
        sa.Column("last_sync_at", mysql.DATETIME(fsp=3), nullable=True, comment="上次同步时刻（UTC）"),
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False, comment="主键"),
        sa.Column("created_at", mysql.DATETIME(fsp=3), nullable=False, comment="创建时间（UTC）"),
        sa.Column("updated_at", mysql.DATETIME(fsp=3), nullable=False, comment="更新时间（UTC）"),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_sync_cursor")),
    )
    op.create_table(
        "approval_instance",
        sa.Column(
            "instance_no",
            sa.String(length=64),
            nullable=False,
            comment="审批单号。⚠️ 唯一性语义未定义，P3 不加 UNIQUE（裁决 O4）",
        ),
        sa.Column("title", sa.String(length=255), nullable=False, comment="审批单标题"),
        sa.Column(
            "applicant",
            sa.String(length=64),
            nullable=False,
            comment="申请人姓名。Mock 域用纯字符串，不关联 sys_user",
        ),
        sa.Column("dept", sa.String(length=64), nullable=True, comment="申请部门"),
        sa.Column("amount", sa.Numeric(precision=18, scale=2), nullable=True, comment="金额（禁止 float）"),
        sa.Column(
            "status", sa.String(length=16), nullable=False, comment="审批单状态。取值由 P14 定义，P3 不猜"
        ),
        sa.Column("contract_id", sa.BigInteger(), nullable=True, comment="关联合同。§7.1 关系为 0:1，故可空"),
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False, comment="主键"),
        sa.Column("created_at", mysql.DATETIME(fsp=3), nullable=False, comment="创建时间（UTC）"),
        sa.Column("updated_at", mysql.DATETIME(fsp=3), nullable=False, comment="更新时间（UTC）"),
        sa.ForeignKeyConstraint(
            ["contract_id"], ["contract.id"], name=op.f("fk_approval_instance_contract_id_contract")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_approval_instance")),
    )
    op.create_table(
        "contract_file",
        sa.Column("contract_id", sa.BigInteger(), nullable=False, comment="所属合同"),
        sa.Column("file_name", sa.String(length=255), nullable=False, comment="原始文件名"),
        sa.Column("file_ext", sa.String(length=16), nullable=False, comment="扩展名，如 docx"),
        sa.Column("file_size", sa.BigInteger(), nullable=False, comment="字节数"),
        sa.Column(
            "sha256",
            sa.CHAR(length=64),
            nullable=False,
            comment="文件内容的 SHA-256 十六进制摘要。UNIQUE：同一文件重复上传时复用解析产物",
        ),
        sa.Column(
            "storage_path",
            sa.String(length=512),
            nullable=False,
            comment="相对 storage/uploads/{contract_id}/ 的路径",
        ),
        sa.Column("page_count", sa.Integer(), nullable=True, comment="页数"),
        sa.Column("is_scanned", sa.Boolean(), nullable=False, comment="是否判定为扫描件（需走 OCR）"),
        sa.Column(
            "parse_status",
            sa.String(length=16),
            nullable=False,
            comment="单文件解析状态。具体取值由 P7 解析阶段确定",
        ),
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False, comment="主键"),
        sa.Column("created_at", mysql.DATETIME(fsp=3), nullable=False, comment="创建时间（UTC）"),
        sa.Column("updated_at", mysql.DATETIME(fsp=3), nullable=False, comment="更新时间（UTC）"),
        sa.ForeignKeyConstraint(
            ["contract_id"], ["contract.id"], name=op.f("fk_contract_file_contract_id_contract")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_contract_file")),
        sa.UniqueConstraint("sha256", name=op.f("uq_contract_file_sha256")),
    )
    op.create_table(
        "review_rule",
        sa.Column(
            "rule_set_id",
            sa.BigInteger(),
            nullable=False,
            comment="所属规则集。§7.2 字段表未列出此列，但「rule_code UNIQUE within set」与 §7.1 的 rule_set 1:N rule 关系都要求它存在（经架构裁决补充）",
        ),
        sa.Column(
            "rule_code",
            sa.String(length=64),
            nullable=False,
            comment="规则编码，如 LIAB_UNEQUAL_001；在所属规则集内唯一",
        ),
        sa.Column("rule_name", sa.String(length=128), nullable=False, comment="规则名称"),
        sa.Column(
            "dimension",
            sa.String(length=32),
            nullable=False,
            comment="审查维度，如「违约责任」「知识产权」（取值由 P9 定义）",
        ),
        sa.Column("description", sa.String(length=512), nullable=True, comment="规则说明"),
        sa.Column(
            "rule_type", sa.String(length=16), nullable=False, comment="求值器类型，取值见 constants.RuleType"
        ),
        sa.Column(
            "expression",
            sa.JSON(),
            nullable=False,
            comment='求值表达式，如 {"keywords":["无限责任"],"logic":"ANY"} 或 {"field":"amount","op":"gt","value":1000000}',
        ),
        sa.Column(
            "target_clause_types", sa.JSON(), nullable=True, comment="限定作用范围：条款类型数组，空表示不限"
        ),
        sa.Column(
            "severity",
            sa.String(length=16),
            nullable=False,
            comment="命中后的风险等级，取值见 constants.RiskLevel",
        ),
        sa.Column("legal_basis", sa.Text(), nullable=True, comment="法律依据，如《民法典》第 585 条"),
        sa.Column("suggestion_template", sa.Text(), nullable=True, comment="默认修改建议模板"),
        sa.Column("is_active", sa.Boolean(), nullable=False, comment="是否启用"),
        sa.Column("sort_order", sa.Integer(), nullable=False, comment="展示与执行顺序"),
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False, comment="主键"),
        sa.Column("created_at", mysql.DATETIME(fsp=3), nullable=False, comment="创建时间（UTC）"),
        sa.Column("updated_at", mysql.DATETIME(fsp=3), nullable=False, comment="更新时间（UTC）"),
        sa.ForeignKeyConstraint(
            ["rule_set_id"], ["review_rule_set.id"], name=op.f("fk_review_rule_rule_set_id_review_rule_set")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_review_rule")),
        sa.UniqueConstraint("rule_set_id", "rule_code", name=op.f("uq_review_rule_rule_set_id_rule_code")),
    )
    op.create_table(
        "approval_comment",
        sa.Column("instance_id", sa.BigInteger(), nullable=False, comment="所属审批单"),
        sa.Column("author", sa.String(length=64), nullable=False, comment="评论人姓名"),
        sa.Column("content", sa.Text(), nullable=False, comment="评论内容（回写时为 Markdown）"),
        sa.Column(
            "comment_type",
            sa.String(length=16),
            nullable=False,
            comment="评论类型：USER / SYSTEM_REVIEW（§7.2）",
        ),
        sa.Column(
            "source",
            sa.String(length=16),
            nullable=False,
            comment="来源：MANUAL / CONTRACT_REVIEW_SYSTEM（§7.2）。回写产生的评论后者",
        ),
        sa.Column(
            "external_id",
            sa.String(length=128),
            nullable=True,
            comment="外部系统评论 ID。⚠️ P3 不加 UNIQUE（裁决 O5）：全局唯一还是审批单内唯一尚未定义",
        ),
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False, comment="主键"),
        sa.Column("created_at", mysql.DATETIME(fsp=3), nullable=False, comment="创建时间（UTC）"),
        sa.Column("updated_at", mysql.DATETIME(fsp=3), nullable=False, comment="更新时间（UTC）"),
        sa.ForeignKeyConstraint(
            ["instance_id"],
            ["approval_instance.id"],
            name=op.f("fk_approval_comment_instance_id_approval_instance"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_approval_comment")),
    )
    op.create_table(
        "document_block",
        sa.Column("contract_id", sa.BigInteger(), nullable=False, comment="所属合同"),
        sa.Column("file_id", sa.BigInteger(), nullable=False, comment="来源附件"),
        sa.Column("order_index", sa.Integer(), nullable=False, comment="全文档线性顺序，前端渲染顺序"),
        sa.Column(
            "block_type", sa.String(length=16), nullable=False, comment="块类型，取值见 constants.BlockType"
        ),
        sa.Column(
            "page_number",
            sa.Integer(),
            nullable=True,
            comment="⚠️ 仅真实页码：PDF/扫描件/图片有值，DOCX 恒为 NULL，禁止估算填充（§10.4）",
        ),
        sa.Column(
            "paragraph_index",
            sa.Integer(),
            nullable=False,
            comment="段落索引：DOCX 为真实段号；PDF/图片为页内第 N 个文本块",
        ),
        sa.Column(
            "locator_type",
            sa.String(length=16),
            nullable=False,
            comment="定位方式，取值见 constants.LocatorType；解析时按文件类型一次性写入",
        ),
        sa.Column("text", sa.Text(), nullable=False, comment="归一化后的文本"),
        sa.Column("raw_text", sa.Text(), nullable=False, comment="原文（OCR 原始输出 / 未归一化），审计用"),
        sa.Column(
            "char_start_in_block", sa.Integer(), nullable=False, comment="块内起始偏移（归一化映射用）"
        ),
        sa.Column("char_end_in_block", sa.Integer(), nullable=False, comment="块内结束偏移（归一化映射用）"),
        sa.Column(
            "char_start_global",
            sa.Integer(),
            nullable=False,
            comment="全文档全局起始偏移 —— 所有定位的唯一依据",
        ),
        sa.Column(
            "char_end_global",
            sa.Integer(),
            nullable=False,
            comment="全文档全局结束偏移，区间语义 [start, end)",
        ),
        sa.Column("bbox_json", sa.JSON(), nullable=True, comment="OCR/PDF 的坐标框，供渲染层精确框选"),
        sa.Column("ocr_confidence", sa.Float(), nullable=True, comment="OCR 置信度（仅扫描件有值）"),
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False, comment="主键"),
        sa.Column("created_at", mysql.DATETIME(fsp=3), nullable=False, comment="创建时间（UTC）"),
        sa.Column("updated_at", mysql.DATETIME(fsp=3), nullable=False, comment="更新时间（UTC）"),
        sa.ForeignKeyConstraint(
            ["contract_id"], ["contract.id"], name=op.f("fk_document_block_contract_id_contract")
        ),
        sa.ForeignKeyConstraint(
            ["file_id"], ["contract_file.id"], name=op.f("fk_document_block_file_id_contract_file")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_document_block")),
    )
    op.create_index(
        op.f("ix_document_block_contract_id_char_start_global"),
        "document_block",
        ["contract_id", "char_start_global"],
        unique=False,
    )
    op.create_index(
        op.f("ix_document_block_contract_id_order_index"),
        "document_block",
        ["contract_id", "order_index"],
        unique=False,
    )
    op.create_table(
        "review_task",
        sa.Column(
            "contract_id",
            sa.BigInteger(),
            nullable=False,
            comment="所属合同。建真实 FK：它才是 contract↔task 关系的主体",
        ),
        sa.Column("file_id", sa.BigInteger(), nullable=False, comment="被审查的附件"),
        sa.Column(
            "status",
            sa.String(length=16),
            nullable=False,
            comment="任务状态，取值见 constants.TaskStatus（§6.1）",
        ),
        sa.Column(
            "current_stage",
            sa.String(length=16),
            nullable=False,
            comment="阶段级断点标记，取值见 constants.TaskStage；断点续跑依据（§6.1）",
        ),
        sa.Column("progress", mysql.TINYINT(), nullable=False, comment="0~100，前端进度条"),
        sa.Column("priority", sa.Integer(), nullable=False, comment="抢占排序用，值越大越先被抢"),
        sa.Column("worker_id", sa.String(length=64), nullable=True, comment="抢占它的 worker 标识（§1.4）"),
        sa.Column("locked_at", mysql.DATETIME(fsp=3), nullable=True, comment="抢占时刻"),
        sa.Column(
            "heartbeat_at", mysql.DATETIME(fsp=3), nullable=True, comment="心跳时间，自愈扫描依据（§13.5）"
        ),
        sa.Column(
            "next_retry_at",
            mysql.DATETIME(fsp=3),
            nullable=True,
            comment="退避重试的可见时间；NULL = 立即可抢",
        ),
        sa.Column(
            "version", sa.Integer(), nullable=False, comment="乐观锁版本号，每次状态变更 +1（手工维护）"
        ),
        sa.Column("retry_count", sa.Integer(), nullable=False, comment="已重试次数"),
        sa.Column("max_retry", sa.Integer(), nullable=False, comment="任务级重试上限（§13.2）"),
        sa.Column(
            "block_reason_code",
            sa.String(length=32),
            nullable=True,
            comment="阻塞原因枚举，取值见 constants.BlockReasonCode（§6.1）",
        ),
        sa.Column("block_reason_msg", sa.String(length=512), nullable=True, comment="人话原因，前端直接展示"),
        sa.Column(
            "risk_level_final",
            sa.String(length=16),
            nullable=True,
            comment="综合风险等级，取值见 constants.RiskLevel；未完成时为空",
        ),
        sa.Column(
            "conclusion",
            sa.String(length=16),
            nullable=True,
            comment="审查结论，取值见 constants.ReviewConclusion；未完成时为空",
        ),
        sa.Column("summary", sa.Text(), nullable=True, comment="审查摘要（供报告与回写复用）"),
        sa.Column(
            "idempotency_key",
            sa.String(length=64),
            nullable=False,
            comment="sha256(contract_id + file_sha256 + rule_set_version + prompt_version)；NOT NULL UNIQUE —— 允许 NULL 会让幂等约束被静默绕过",
        ),
        sa.Column("error_msg", sa.Text(), nullable=True, comment="失败原因，排查用"),
        sa.Column("started_at", mysql.DATETIME(fsp=3), nullable=True, comment="开始执行时刻"),
        sa.Column("finished_at", mysql.DATETIME(fsp=3), nullable=True, comment="结束时刻"),
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False, comment="主键"),
        sa.Column("created_at", mysql.DATETIME(fsp=3), nullable=False, comment="创建时间（UTC）"),
        sa.Column("updated_at", mysql.DATETIME(fsp=3), nullable=False, comment="更新时间（UTC）"),
        sa.ForeignKeyConstraint(
            ["contract_id"], ["contract.id"], name=op.f("fk_review_task_contract_id_contract")
        ),
        sa.ForeignKeyConstraint(
            ["file_id"], ["contract_file.id"], name=op.f("fk_review_task_file_id_contract_file")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_review_task")),
        sa.UniqueConstraint("idempotency_key", name=op.f("uq_review_task_idempotency_key")),
    )
    op.create_index("idx_claim", "review_task", ["status", "next_retry_at", "priority", "id"], unique=False)
    op.create_index("idx_heartbeat", "review_task", ["status", "heartbeat_at"], unique=False)
    op.create_table(
        "ai_call_log",
        sa.Column("task_id", sa.BigInteger(), nullable=False, comment="所属审查任务"),
        sa.Column(
            "provider", sa.String(length=32), nullable=False, comment="提供方，如 deepseek / anthropic"
        ),
        sa.Column("model", sa.String(length=64), nullable=False, comment="模型标识"),
        sa.Column(
            "scene",
            sa.String(length=32),
            nullable=False,
            comment="调用场景，取值见 constants.LLMScene（§9.1）",
        ),
        sa.Column(
            "prompt_version", sa.String(length=32), nullable=False, comment="提示词版本，用于效果回归对比"
        ),
        sa.Column("prompt_tokens", sa.Integer(), nullable=True, comment="输入 token 数"),
        sa.Column("completion_tokens", sa.Integer(), nullable=True, comment="输出 token 数"),
        sa.Column("total_tokens", sa.Integer(), nullable=True, comment="总 token 数"),
        sa.Column("latency_ms", sa.Integer(), nullable=True, comment="耗时（毫秒）"),
        sa.Column(
            "status", sa.String(length=16), nullable=False, comment="调用结果状态，如 success / failed"
        ),
        sa.Column("retry_index", sa.Integer(), nullable=False, comment="第几次重试（0 表示首次）"),
        sa.Column("http_status", sa.Integer(), nullable=True, comment="HTTP 状态码"),
        sa.Column(
            "error_code",
            sa.String(length=64),
            nullable=True,
            comment="错误码，取值见 constants/errors.ErrorCode",
        ),
        sa.Column("error_msg", sa.Text(), nullable=True, comment="错误详情（脱敏）"),
        sa.Column("request_id", sa.String(length=64), nullable=True, comment="链路追踪 ID，可与应用日志对齐"),
        sa.Column(
            "raw_response",
            mysql.MEDIUMTEXT(),
            nullable=True,
            comment="模型原始响应（含 JSON 围栏），排查与回归用",
        ),
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False, comment="主键"),
        sa.Column("created_at", mysql.DATETIME(fsp=3), nullable=False, comment="创建时间（UTC）"),
        sa.Column("updated_at", mysql.DATETIME(fsp=3), nullable=False, comment="更新时间（UTC）"),
        sa.ForeignKeyConstraint(
            ["task_id"], ["review_task.id"], name=op.f("fk_ai_call_log_task_id_review_task")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_ai_call_log")),
    )
    op.create_table(
        "clause",
        sa.Column("contract_id", sa.BigInteger(), nullable=False),
        sa.Column("task_id", sa.BigInteger(), nullable=False, comment="产出它的审查任务"),
        sa.Column(
            "clause_no", sa.String(length=64), nullable=True, comment="条款号（如「第三条」）；识别不出时为空"
        ),
        sa.Column(
            "clause_type",
            sa.String(length=32),
            nullable=False,
            comment="条款类型，取值见 constants.ClauseType",
        ),
        sa.Column("title", sa.String(length=255), nullable=True, comment="条款标题"),
        sa.Column("start_block_id", sa.BigInteger(), nullable=True, comment="起始块"),
        sa.Column("end_block_id", sa.BigInteger(), nullable=True, comment="结束块"),
        sa.Column("char_start_global", sa.Integer(), nullable=False, comment="条款起始全局偏移"),
        sa.Column("char_end_global", sa.Integer(), nullable=False, comment="条款结束全局偏移"),
        sa.Column("page_start", sa.Integer(), nullable=True, comment="起始页码；DOCX 为 NULL（§10.4）"),
        sa.Column("page_end", sa.Integer(), nullable=True, comment="结束页码"),
        sa.Column("text", sa.Text(), nullable=False, comment="条款全文"),
        sa.Column(
            "extract_method",
            sa.String(length=16),
            nullable=False,
            comment="切分方式，取值见 constants.ExtractMethod",
        ),
        sa.Column("confidence", sa.Float(), nullable=True, comment="切分置信度"),
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False, comment="主键"),
        sa.Column("created_at", mysql.DATETIME(fsp=3), nullable=False, comment="创建时间（UTC）"),
        sa.Column("updated_at", mysql.DATETIME(fsp=3), nullable=False, comment="更新时间（UTC）"),
        sa.ForeignKeyConstraint(
            ["contract_id"], ["contract.id"], name=op.f("fk_clause_contract_id_contract")
        ),
        sa.ForeignKeyConstraint(
            ["end_block_id"], ["document_block.id"], name=op.f("fk_clause_end_block_id_document_block")
        ),
        sa.ForeignKeyConstraint(
            ["start_block_id"], ["document_block.id"], name=op.f("fk_clause_start_block_id_document_block")
        ),
        sa.ForeignKeyConstraint(["task_id"], ["review_task.id"], name=op.f("fk_clause_task_id_review_task")),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_clause")),
    )
    op.create_table(
        "contract_metadata",
        sa.Column("contract_id", sa.BigInteger(), nullable=False),
        sa.Column("task_id", sa.BigInteger(), nullable=False, comment="产出它的审查任务"),
        sa.Column(
            "field_key",
            sa.String(length=64),
            nullable=False,
            comment="字段键，如 counterparty_name / credit_code / contract_amount",
        ),
        sa.Column("field_label", sa.String(length=128), nullable=False, comment="展示名"),
        sa.Column("field_value", sa.Text(), nullable=False, comment="字段值"),
        sa.Column(
            "value_type", sa.String(length=16), nullable=False, comment="值类型：TEXT / AMOUNT / DATE / CODE"
        ),
        sa.Column("confidence", sa.Float(), nullable=True, comment="抽取置信度"),
        sa.Column("source_block_id", sa.BigInteger(), nullable=True, comment="来源块"),
        sa.Column("char_start_global", sa.Integer(), nullable=True, comment="定位起始偏移（抽取失败时为空）"),
        sa.Column("char_end_global", sa.Integer(), nullable=True, comment="定位结束偏移"),
        sa.Column("page_number", sa.Integer(), nullable=True, comment="真实页码；DOCX 为 NULL（§10.4）"),
        sa.Column(
            "extract_method",
            sa.String(length=16),
            nullable=False,
            comment="提取方式，取值见 constants.ExtractMethod",
        ),
        sa.Column(
            "verified_by",
            sa.BigInteger(),
            nullable=True,
            comment="人工校对者 sys_user.id（sys_user 属 P4，暂不建 FK）",
        ),
        sa.Column("verified_at", mysql.DATETIME(fsp=3), nullable=True, comment="人工校对时刻"),
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False, comment="主键"),
        sa.Column("created_at", mysql.DATETIME(fsp=3), nullable=False, comment="创建时间（UTC）"),
        sa.Column("updated_at", mysql.DATETIME(fsp=3), nullable=False, comment="更新时间（UTC）"),
        sa.ForeignKeyConstraint(
            ["contract_id"], ["contract.id"], name=op.f("fk_contract_metadata_contract_id_contract")
        ),
        sa.ForeignKeyConstraint(
            ["source_block_id"],
            ["document_block.id"],
            name=op.f("fk_contract_metadata_source_block_id_document_block"),
        ),
        sa.ForeignKeyConstraint(
            ["task_id"], ["review_task.id"], name=op.f("fk_contract_metadata_task_id_review_task")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_contract_metadata")),
    )
    op.create_table(
        "writeback_record",
        sa.Column("task_id", sa.BigInteger(), nullable=False, comment="所属审查任务"),
        sa.Column("contract_id", sa.BigInteger(), nullable=False, comment="所属合同"),
        sa.Column(
            "approval_instance_id",
            sa.BigInteger(),
            nullable=False,
            comment="目标审批单。建真实 FK：回写必然针对某个审批单",
        ),
        sa.Column("content_md", sa.Text(), nullable=False, comment="回写内容快照（Markdown），审计证据"),
        sa.Column(
            "content_hash",
            sa.CHAR(length=64),
            nullable=False,
            comment="content_md 的 SHA-256，参与幂等键计算",
        ),
        sa.Column(
            "status",
            sa.String(length=16),
            nullable=False,
            comment="回写状态，取值见 constants.WritebackStatus（§6.2）。初始为 not_written",
        ),
        sa.Column("attempt", sa.Integer(), nullable=False, comment="已尝试次数"),
        sa.Column(
            "idempotency_key",
            sa.String(length=64),
            nullable=False,
            comment="sha256(task_id + content_hash)；NOT NULL UNIQUE，防止重复评论",
        ),
        sa.Column(
            "external_comment_id", sa.String(length=128), nullable=True, comment="审批系统返回的评论 ID"
        ),
        sa.Column("request_body", sa.Text(), nullable=True, comment="请求体（脱敏）"),
        sa.Column("response_body", sa.Text(), nullable=True, comment="响应体（脱敏）"),
        sa.Column("error_msg", sa.Text(), nullable=True, comment="失败原因"),
        sa.Column(
            "operator_id",
            sa.BigInteger(),
            nullable=True,
            comment="操作人 sys_user.id（sys_user 属 P4，暂不建 FK）",
        ),
        sa.Column("started_at", mysql.DATETIME(fsp=3), nullable=True, comment="开始写回时刻"),
        sa.Column("finished_at", mysql.DATETIME(fsp=3), nullable=True, comment="写回结束时刻"),
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False, comment="主键"),
        sa.Column("created_at", mysql.DATETIME(fsp=3), nullable=False, comment="创建时间（UTC）"),
        sa.Column("updated_at", mysql.DATETIME(fsp=3), nullable=False, comment="更新时间（UTC）"),
        sa.ForeignKeyConstraint(
            ["approval_instance_id"],
            ["approval_instance.id"],
            name=op.f("fk_writeback_record_approval_instance_id_approval_instance"),
        ),
        sa.ForeignKeyConstraint(
            ["contract_id"], ["contract.id"], name=op.f("fk_writeback_record_contract_id_contract")
        ),
        sa.ForeignKeyConstraint(
            ["task_id"], ["review_task.id"], name=op.f("fk_writeback_record_task_id_review_task")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_writeback_record")),
        sa.UniqueConstraint("idempotency_key", name=op.f("uq_writeback_record_idempotency_key")),
    )
    op.create_table(
        "risk_item",
        sa.Column("task_id", sa.BigInteger(), nullable=False, comment="所属审查任务"),
        sa.Column("contract_id", sa.BigInteger(), nullable=False, comment="所属合同"),
        sa.Column(
            "clause_id",
            sa.BigInteger(),
            nullable=True,
            comment="命中的条款。⚠️ 可为空：MISSING 类（必备条款缺失）风险没有对应条款",
        ),
        sa.Column("rule_id", sa.BigInteger(), nullable=True, comment="来源规则；纯 LLM 风险为空"),
        sa.Column(
            "risk_code",
            sa.String(length=64),
            nullable=True,
            comment="风险编码；规则来源时取 rule_code，LLM 来源可能为空",
        ),
        sa.Column("risk_title", sa.String(length=255), nullable=False, comment="风险项名称"),
        sa.Column("dimension", sa.String(length=32), nullable=False, comment="审查维度"),
        sa.Column(
            "risk_level", sa.String(length=16), nullable=False, comment="风险等级，取值见 constants.RiskLevel"
        ),
        sa.Column(
            "source", sa.String(length=16), nullable=False, comment="风险来源，取值见 constants.RiskSource"
        ),
        sa.Column("reason", sa.Text(), nullable=True, comment="风险成因分析"),
        sa.Column("legal_basis", sa.Text(), nullable=True, comment="法律合规依据"),
        sa.Column("original_text", sa.Text(), nullable=True, comment="命中的原文片段（LLM quote 反查结果）"),
        sa.Column("page_number", sa.Integer(), nullable=True, comment="真实页码；DOCX 为 NULL（§10.4）"),
        sa.Column("paragraph_index", sa.Integer(), nullable=True, comment="段落索引"),
        sa.Column(
            "char_start_global",
            sa.Integer(),
            nullable=True,
            comment="⚠️ 可为空：CLAUSE_FALLBACK 降级时无精确区间（§10.5）",
        ),
        sa.Column("char_end_global", sa.Integer(), nullable=True, comment="全局结束偏移"),
        sa.Column(
            "locator_type",
            sa.String(length=16),
            nullable=False,
            comment="定位方式，取值见 constants.LocatorType；与所属附件一致",
        ),
        sa.Column(
            "anchor_method",
            sa.String(length=16),
            nullable=True,
            comment="坐标反查方式，取值见 constants.AnchorMethod（§10.5 四级作用域）；规则来源为空",
        ),
        sa.Column(
            "anchor_score",
            sa.Float(),
            nullable=True,
            comment="定位置信度 0~1；< 0.8 时前端显示「定位待核对」角标",
        ),
        sa.Column(
            "occurrence_index",
            sa.Integer(),
            nullable=True,
            comment="quote 在作用域内第几次出现（消歧结果，1-based）",
        ),
        sa.Column(
            "quote_context",
            sa.JSON(),
            nullable=True,
            comment='引文上下文 {"before": "...", "after": "..."}，用于消歧与复核',
        ),
        sa.Column(
            "confidence", sa.Float(), nullable=True, comment="LLM 对该风险判断本身的置信度（≠ anchor_score）"
        ),
        sa.Column(
            "review_status",
            sa.String(length=16),
            nullable=False,
            comment="复核状态，取值见 constants.RiskReviewStatus（§6.3）",
        ),
        sa.Column(
            "reviewer_id",
            sa.BigInteger(),
            nullable=True,
            comment="复核人 sys_user.id（sys_user 属 P4，暂不建 FK）",
        ),
        sa.Column("review_comment", sa.Text(), nullable=True, comment="复核意见"),
        sa.Column("reviewed_at", mysql.DATETIME(fsp=3), nullable=True, comment="复核时刻"),
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False, comment="主键"),
        sa.Column("created_at", mysql.DATETIME(fsp=3), nullable=False, comment="创建时间（UTC）"),
        sa.Column("updated_at", mysql.DATETIME(fsp=3), nullable=False, comment="更新时间（UTC）"),
        sa.ForeignKeyConstraint(["clause_id"], ["clause.id"], name=op.f("fk_risk_item_clause_id_clause")),
        sa.ForeignKeyConstraint(
            ["contract_id"], ["contract.id"], name=op.f("fk_risk_item_contract_id_contract")
        ),
        sa.ForeignKeyConstraint(
            ["rule_id"], ["review_rule.id"], name=op.f("fk_risk_item_rule_id_review_rule")
        ),
        sa.ForeignKeyConstraint(
            ["task_id"], ["review_task.id"], name=op.f("fk_risk_item_task_id_review_task")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_risk_item")),
    )
    op.create_table(
        "risk_suggestion",
        sa.Column("risk_item_id", sa.BigInteger(), nullable=False, comment="所属风险项"),
        sa.Column(
            "suggestion_type",
            sa.String(length=16),
            nullable=False,
            comment="建议类型，取值见 constants.SuggestionType",
        ),
        sa.Column(
            "original_text", sa.Text(), nullable=True, comment="原条款文本；ADD 类型（新增条款）时为空"
        ),
        sa.Column("suggested_text", sa.Text(), nullable=False, comment="AI 生成的示范条款"),
        sa.Column("reason", sa.Text(), nullable=True, comment="修改理由"),
        sa.Column(
            "standard_clause_id",
            sa.BigInteger(),
            nullable=True,
            comment="引用的标准条款库条目 standard_clause.id。⚠️ standard_clause 属 P13，P3 暂不建 FK，P13 完成后通过增量迁移补",
        ),
        sa.Column("is_adopted", sa.Boolean(), nullable=False, comment="法务是否采纳"),
        sa.Column(
            "adopted_by",
            sa.BigInteger(),
            nullable=True,
            comment="采纳人 sys_user.id（sys_user 属 P4，暂不建 FK）",
        ),
        sa.Column("adopted_at", mysql.DATETIME(fsp=3), nullable=True, comment="采纳时刻"),
        sa.Column(
            "final_text",
            sa.Text(),
            nullable=True,
            comment="法务编辑后的最终文本。⚠️ 回写与报告使用 final_text，而不是 suggested_text（§7.2）",
        ),
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False, comment="主键"),
        sa.Column("created_at", mysql.DATETIME(fsp=3), nullable=False, comment="创建时间（UTC）"),
        sa.Column("updated_at", mysql.DATETIME(fsp=3), nullable=False, comment="更新时间（UTC）"),
        sa.ForeignKeyConstraint(
            ["risk_item_id"], ["risk_item.id"], name=op.f("fk_risk_suggestion_risk_item_id_risk_item")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_risk_suggestion")),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("risk_suggestion")
    op.drop_table("risk_item")
    op.drop_table("writeback_record")
    op.drop_table("contract_metadata")
    op.drop_table("clause")
    op.drop_table("ai_call_log")
    op.drop_index("idx_heartbeat", table_name="review_task")
    op.drop_index("idx_claim", table_name="review_task")
    op.drop_table("review_task")
    # --- 手工修正（自动生成的内容不可直接执行）---------------------------------
    # document_block 的两条组合索引都以 contract_id 为**最左列**，MySQL 会自动
    # 选用它们充当外键 fk_document_block_contract_id_contract 的支撑索引。
    # 若按自动生成的顺序先 drop_index，MySQL 会报：
    #   1553 "Cannot drop index '...': needed in a foreign key constraint"
    # 且因为是 DROP 中途失败，会把数据库留在**半回滚**状态。
    # 因此必须先显式 drop 掉该外键约束，再 drop 索引。
    # （Alembic 不会自动生成 drop_constraint：它默认依赖 drop_table 连带清除外键。）
    op.drop_constraint("fk_document_block_contract_id_contract", "document_block", type_="foreignkey")
    op.drop_index(op.f("ix_document_block_contract_id_order_index"), table_name="document_block")
    op.drop_index(op.f("ix_document_block_contract_id_char_start_global"), table_name="document_block")
    op.drop_table("document_block")
    op.drop_table("approval_comment")
    op.drop_table("review_rule")
    op.drop_table("contract_file")
    op.drop_table("approval_instance")
    op.drop_table("sync_cursor")
    op.drop_table("review_rule_set")
    op.drop_table("contract")
    # ### end Alembic commands ###
